export const PLANNER_IMAGE_KEYS = [
  'berry-oats',
  'egg-toast',
  'yogurt-parfait',
  'smoothie-bowl',
  'smoked-salmon-rye-toast',
  'banana-pancakes',
  'chia-pudding',
  'harvest-salad',
  'salmon-quinoa',
  'lentil-soup',
  'turkey-hummus-wrap',
  'greek-salad',
  'tuna-poke',
  'chickpea-bowl',
  'tofu-stir-fry',
  'med-pasta',
  'chicken-rice',
  'thai-curry',
  'spaghetti-bolognese',
  'beef-tacos',
  'prawn-stirfry',
  'apple-almond',
  'edamame',
  'trail-mix',
  'hummus-veggies',
  'banana-peanut-butter',
] as const;

export type PlannerImageKey = (typeof PLANNER_IMAGE_KEYS)[number];

export const FOOD_IMAGE_KEYS = [
  'greek-yogurt-plain',
  'salmon-rice-bowl',
  'eggs-sourdough',
  'avocado-toast',
  'overnight-oats',
  'berry-protein-smoothie',
  'chicken-rice-bowl',
  'turkey-avocado-wrap',
  'lentil-quinoa-salad',
  'tomato-basil-soup',
  'grilled-chicken-vegetables',
  'shrimp-tacos',
  'tofu-vegetable-stir-fry',
  'whole-wheat-pasta-primavera',
  'beef-bean-chili',
  'cottage-cheese-berries',
  'apple-almond-butter',
  'hummus-vegetables',
  'trail-mix',
  'tuna-cucumber-crackers',
] as const;

export type FoodImageKey = (typeof FOOD_IMAGE_KEYS)[number];