import React, { useState } from "react";
import { Activity, Bell, BellOff, Check, ChevronRight, Cloud, Droplet, Edit3, ExternalLink, EyeOff, FileText, Globe, HelpCircle, Info, Layers, Lock, Mail, Moon, Plus, Shield, Sun, Target, Trash2, Type, User, X } from "lucide-react";
import "./_group.css";

type Tab = "you" | "membership" | "account";
const reminders = [
  ["Hydration reminders", "Every 2h · 7:00 AM – 10:00 PM", Droplet],
  ["Breakfast", "8:00 AM", Sun],
  ["Lunch", "12:30 PM", Sun],
  ["Dinner", "7:00 PM", Moon],
];
const notices = [
  ["Hydration reminder", "Time for a glass of water. Small, steady steps add up.", "Today · 2:00 PM"],
  ["Daily goal check-in", "You are 420 kcal from your daily target. Keep going.", "Today · 9:00 AM"],
];

function Row({ icon: Icon, title, body, action = true }: { icon: React.ElementType; title: string; body: string; action?: boolean }) {
  return <div className="cp-row cp-setting"><div className="cp-symbol"><Icon size={16}/></div><div className="cp-copy"><div className="cp-row-title">{title}</div><div className="cp-row-body">{body}</div></div>{action && <ChevronRight className="cp-chevron" size={16}/>}</div>;
}

function Notifications({ close }: { close: () => void }) {
  return <div className="cp-overlay" onClick={close}><section className="cp-sheet" onClick={(e) => e.stopPropagation()}><header className="cp-sheet-head"><div className="cp-symbol"><Bell size={17}/></div><div style={{ marginLeft: 10 }}><h2>Notifications</h2><div className="cp-row-body">2 unread updates</div></div><button className="cp-sheet-close" onClick={close}><X size={17}/></button></header>{notices.map((n, i) => <div className={"cp-notice " + (!i ? "unread" : "")} key={n[0]}><div className="cp-symbol"><Bell size={15}/></div><div style={{ flex: 1 }}><p>{n[0]}</p><small>{n[1]}</small><small>{n[2]}</small></div><ChevronRight size={15}/></div>)}<footer className="cp-sheet-actions"><button>✓ Mark all read</button><button>Clear history</button></footer></section></div>;
}

function YouTab() {
  const [notifications, setNotifications] = useState(true);
  const [quiet, setQuiet] = useState(true);
  return <>
    <div className="cp-section-title">Your plan</div><div className="cp-section-sub">Update details and choose how targets are managed.</div>
    <div className="cp-card"><Row icon={User} title="Personal details" body="34 years · Moderately active"/><div className="cp-divider"/><Row icon={Target} title="Nutrition goals" body="Automatic recommendations"/></div>
    <div className="cp-section-title">Appearance</div><div className="cp-section-sub">Choose your display.</div>
    <div className="cp-segmented">{["System","Light","Dark"].map((x, i) => <button className={i === 0 ? "active" : ""} key={x}>{i === 0 ? "▣" : i === 1 ? "☼" : "◐"}&nbsp; {x}</button>)}</div>
    <div className="cp-card cp-setting"><div className="cp-symbol"><Type size={16}/></div><div className="cp-copy"><div className="cp-row-title">Text size</div><div className="cp-row-body">Grilled chicken salad · 510 kcal</div></div><div className="cp-chips"><button className="cp-chip">A−</button><button className="cp-chip active">A</button><button className="cp-chip">A+</button></div></div>
    <div className="cp-card cp-setting"><div className="cp-symbol">↔</div><div className="cp-copy"><div className="cp-row-title">Measurement units</div></div><div className="cp-chips"><button className="cp-chip active">Metric</button><button className="cp-chip">Imperial</button></div></div>
    <div className="cp-section-title">Reminders</div><div className="cp-section-sub">On-device water, meal, and goal nudges.</div>
    <div className="cp-card cp-setting"><div className="cp-symbol">{notifications ? <Bell size={16}/> : <BellOff size={16}/>}</div><div className="cp-copy"><div className="cp-row-title">Notifications</div><div className="cp-row-body">{notifications ? "Deliver selected reminders on this device" : "Paused — your reminder choices are saved"}</div></div><input className="cp-toggle" type="checkbox" checked={notifications} onChange={(e) => setNotifications(e.target.checked)}/></div>
    <div className="cp-reminder"><div className="cp-reminder-head"><div className="cp-symbol"><Moon size={15}/></div><div className="cp-copy"><div className="cp-row-title">Quiet hours</div><div className="cp-row-body">{quiet ? "Pause delivery 10:00 PM – 7:00 AM" : "Allow reminders at all hours"}</div></div><input className="cp-toggle" type="checkbox" checked={quiet} onChange={(e) => setQuiet(e.target.checked)}/></div>{quiet && <div className="cp-reminder-detail"><div className="cp-time"><div className="cp-copy"><small>Start quiet hours</small><strong>10:00 PM</strong></div><div className="cp-nudges">−　＋</div></div><div className="cp-time"><div className="cp-copy"><small>End quiet hours</small><strong>7:00 AM</strong></div><div className="cp-nudges">−　＋</div></div></div>}</div>
    <div className="cp-label" style={{ marginTop: 18, marginBottom: 7 }}>MEAL REMINDERS</div><div className="cp-reminder">{reminders.slice(1).map(([title, body, Icon], i) => <React.Fragment key={title as string}>{i > 0 && <div className="cp-divider"/>}<div className="cp-reminder-head"><div className="cp-symbol"><Icon size={15}/></div><div className="cp-copy"><div className="cp-row-title">{title as string}</div><div className="cp-row-body">{body as string}</div></div><input className="cp-toggle" type="checkbox" defaultChecked={i < 2}/></div></React.Fragment>)}</div>
    <div className="cp-label" style={{ marginTop: 18, marginBottom: 7 }}>DAILY GOAL CHECK-IN</div><div className="cp-card cp-setting"><div className="cp-symbol"><Target size={16}/></div><div className="cp-copy"><div className="cp-row-title">Daily goal check-in</div><div className="cp-row-body">Daily at 9:00 AM</div></div><input className="cp-toggle" type="checkbox" defaultChecked/></div>
  </>;
}

function Membership() {
  const [annual, setAnnual] = useState(true);
  return <><div className="cp-plan-row"><div><div className="cp-section-title" style={{ marginTop: 0 }}>CaloraApp Pro</div><div className="cp-section-sub" style={{ marginBottom: 0 }}>Premium features.</div></div><span className="cp-chip active">PRO</span></div><div className="cp-plan-card"><div className="cp-eyebrow">CHOOSE A PLAN</div>{[["Monthly","$4.99 / mo",false],["Annual","$35.99 / yr",true]].map(([name, price, selected]) => <button className={"cp-plan-choice " + ((annual === selected) ? "selected" : "")} key={name as string} onClick={() => setAnnual(selected as boolean)}><span className="cp-radio">{annual === selected && <span className="cp-selected-dot"/>}</span><span className="cp-copy"><b>{name as string}</b><small className="cp-row-body">{selected ? "Billed annually" : "Cancel anytime"}</small></span><span className="cp-price">{price as string}</span></button>)}<div className="cp-note">✓　7-day free trial. Store eligibility and localized prices apply.</div>{["Photo and voice logging","Food sources and confidence","Calorie targets and insights","Ad-free offline diary"].map(x => <div className="cp-feature" key={x}><Check size={15}/>{x}</div>)}<button className="cp-primary">Continue with {annual ? "$35.99 / year" : "$4.99 / month"}　→</button><div className="cp-row-body" style={{ marginTop: 12 }}>After the 7-day trial, your plan renews at its plan price unless changed or canceled in the store.</div><div className="cp-links"><button>Restore purchases</button><span>·</span><button>Manage subscription</button></div></div><div className="cp-section-title">Invite friends</div><div className="cp-card cp-setting"><div className="cp-symbol"><Cloud size={16}/></div><div className="cp-copy"><div className="cp-row-title">Share CaloraApp</div><div className="cp-row-body">Give friends a steadier way to track.</div></div><ChevronRight size={16}/></div><div className="cp-section-title">Saved meals</div><div className="cp-section-sub">Meals to reuse.</div><button className="cp-primary" style={{ width: "auto", marginTop: 0 }}><Plus size={14} style={{ verticalAlign: "middle" }}/> Create</button><div className="cp-card cp-setting" style={{ marginTop: 10 }}><div className="cp-symbol"><Layers size={16}/></div><div className="cp-copy"><div className="cp-row-title">No saved meals</div><div className="cp-row-body">Save a meal or recipe to reuse it.</div></div></div><div className="cp-section-title">Living memory</div><div className="cp-section-sub">Review saved signals on this device.</div><Row icon={Layers} title="Saved signals" body="Nothing remembered yet."/></>;
}

function Account() {
  return <><div className="cp-section-title">Account</div><div className="cp-card cp-account"><div className="cp-account-head"><div className="cp-symbol"><User size={17}/></div><div className="cp-copy"><div className="cp-row-title">alex.morgan@example.com</div><div className="cp-row-body">◉　Email & password</div></div></div><button className="cp-account-action">↪　Sign out <ChevronRight size={16} style={{ marginLeft: "auto" }}/></button><button className="cp-account-action"> <Trash2 size={16}/> Delete account <ChevronRight size={16} style={{ marginLeft: "auto" }}/></button></div><div className="cp-section-title">Trust & privacy</div><div className="cp-card cp-setting" style={{ background: "var(--cp-accent)", borderColor: "transparent" }}><div className="cp-symbol" style={{ background: "var(--cp-primary)", color: "#fff" }}><Activity size={16}/></div><div className="cp-copy"><div className="cp-row-title">Health data</div><div className="cp-row-body">Not connected · CaloraApp works offline without it</div></div><button className="cp-chip">Connect</button></div>{[[Cloud,"Export your data","Portable JSON · stored locally"],[Trash2,"Delete local data","Remove this device’s diary and profile data."],[Shield,"Your food data","Export and delete controls."],[EyeOff,"No ad tracking","Meals are not used for ads."],[HelpCircle,"Help","Get support."]].map(([icon,title,body]) => <Row key={title as string} icon={icon as React.ElementType} title={title as string} body={body as string}/>)}<div className="cp-section-title">About</div>{[[Info,"CaloraApp","AI Nutrition & Calorie Tracker · v1.0.0"],[Globe,"Website","calorie-coach-pie35449.replit.app"],[Shield,"Privacy Policy","How we handle your data"],[FileText,"Terms of Use","Terms governing your use"],[Mail,"Help & Support","support@mycaloraapp.com"]].map(([icon,title,body]) => <Row key={title as string} icon={icon as React.ElementType} title={title as string} body={body as string} action={false}/>) }<div className="cp-version">© 2026 Etiendem Technologies · CaloraApp 1.0 · Made for steadier days</div></>;
}

export function Current() {
  const [tab, setTab] = useState<Tab>("you");
  const [noticeOpen, setNoticeOpen] = useState(false);
  return <main className="calora-profile"><div className="cp-shell"><header className="cp-header"><button className="cp-back"><ChevronRight size={18} style={{ transform: "rotate(180deg)" }}/></button><h1>Profile</h1><button className="cp-icon-btn cp-bell" onClick={() => setNoticeOpen(true)} aria-label="Open notifications"><Bell size={18}/><span className="cp-badge">2</span></button></header><div className="cp-content"><section className="cp-hero"><div className="cp-avatar">A</div><div className="cp-hero-copy"><div className="cp-hero-name">Alex Morgan</div><div className="cp-hero-sub">2,100 kcal · Everything · 72 kg</div></div><button><Edit3 size={17}/></button></section><nav className="cp-tabs" aria-label="Profile sections">{(["you","membership","account"] as Tab[]).map((x) => <button key={x} className={"cp-tab " + (tab === x ? "active" : "")} onClick={() => setTab(x)}>{x[0].toUpperCase() + x.slice(1)}</button>)}</nav><p className="cp-subtitle">{tab === "you" ? "Settings and reminders." : tab === "membership" ? "Plans and rewards." : "Data, health, and help."}</p>{tab === "you" ? <YouTab/> : tab === "membership" ? <Membership/> : <Account/>}</div></div>{noticeOpen && <Notifications close={() => setNoticeOpen(false)}/>}</main>;
}

export default Current;